USE products;

CREATE TABLE forever_table(
   amount_p     INTEGER  NOT NULL PRIMARY KEY 
  ,category     VARCHAR(18) NOT NULL
  ,id           INTEGER  NOT NULL
  ,forever_name VARCHAR(35) NOT NULL
  ,h1           VARCHAR(45) NOT NULL
  ,h2           VARCHAR(77) NOT NULL
  ,description  VARCHAR(206) NOT NULL
  ,price        VARCHAR(12) NOT NULL
  ,price_old    VARCHAR(12)
  ,discount5    VARCHAR(12) NOT NULL
  ,discount15   VARCHAR(10) NOT NULL
  ,discount30   VARCHAR(10) NOT NULL
  ,image3       VARCHAR(60) NOT NULL
);
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (1,'Напитки',1000,'815-ALOE-VERA-GEL','Forever Aloe Vera Gel','Гел от Алое Вера','Със съдържание на над 99,7% чист гел от вътрешността на листата на алое вера Барбаденсис, който се грижи за храносмилателната система.','61.92 лв.','59.54 лв.','58.83 лв.','52.63 лв.','43.35 лв.','https://iglika.me/products_img/Product_details_JPG/1000b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (2,'Напитки',1001,'836-FOREVER-ALOE-MANGO','Forever Aloe Mango','Алое Манго','Подкрепете храносмилателната си система с 86% чисто алое вера и манго вкус!','61.92 лв.','59.54 лв.','58.83 лв.','52.63 лв.','43.35 лв.','https://iglika.me/products_img/Product_details_JPG/1001b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (3,'Напитки',1075,'877-ALOE-PEACH','Forever Aloe Peaches','Алое и праскови','Подобрете храносмилането си с 84.5%  чисто алое вера и сочни праскови.','61.92 лв.','59.54 лв.','58.83 лв.','52.63 лв.','43.35 лв.','https://iglika.me/products_img/Product_details_JPG/1075b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (4,'Напитки',1002,'834-ALOE-BERRY-NECTAR','Forever Aloe Berry Nectar','Алое Бери Нектар','90,7% чист гел от алое вера плюс натурални плодови концентрати за подкрепа на вашето здраве!','61.92 лв.','59.54 лв.','58.83 лв.','52.63 лв.','43.35 лв.','https://iglika.me/products_img/Product_details_JPG/1002b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (5,'Напитки',1117,'8154-ALOE-GEL-4-PACK','Forever Aloe Vera Gel 4-Pack','Четворен пакет - гел от алое','Четворен пакет от любимия гел с алое вера на Форевър! Подкрепя храносмилането и имунитета, зарежда с жизненост и осигурява свежест за целия месец.','247.72 лв.','247.72 лв.','235.33 лв.','210.56 лв.','173.40 лв.','https://iglika.me/products_img/Product_details_JPG/1117b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (6,'Напитки',1118,'8234-FANCY-4-PACK','Forever Aloe Combo 4-Pack','Четворен пакет - алое напитки','Пакет с четирите великолепни алое напитки на Форевър в РЕТ бутилки – Гел от алое вера, Алое Бери Нектар, Алое Манго и Алое с праскови.','247.72 лв.','247.72 лв.','235.33 лв.','210.56 лв.','173.40 лв.','https://iglika.me/products_img/Product_details_JPG/1118b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (7,'Напитки',1119,'8344-ALOE-BERRY-4-PACK','Forever Aloe Berry Nectar 4-Pack','Четворен пакет - алое бери нектар','Четворен пакет с освежаващия алое бери нектар. Подпомага храносмилането, имунитета и отделителната система, като ви осигурява зареждане за целия месец.','247.72 лв.','247.72 лв.','235.33 лв.','210.56 лв.','173.40 лв.','https://iglika.me/products_img/Product_details_JPG/1119b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (8,'Напитки',1120,'8364-ALOE-MANGO-4-PACK','Forever Aloe Mango 4-Pack','Четворен пакет - алое манго','Четворен пакет с ароматната алое манго напитка на Форевър. Сладка, питателна и с всички ползи от чистия гел алое вера. Осигурява ви достатъчно за целия месец.','247.72 лв.','247.72 лв.','235.33 лв.','210.56 лв.','173.40 лв.','https://iglika.me/products_img/Product_details_JPG/1120b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (9,'Напитки',1121,'8774-ALOE-PEACHES-4-PACK','Forever Aloe Peaches 4-Pack','Четворен пакет - алое и праскови','Четворен пакет с ароматната напитка алое и праскови. Четири еднолитрови бутилки достатъчни за целия месец.','247.72 лв.','247.72 лв.','235.33 лв.','210.56 лв.','173.40 лв.','https://iglika.me/products_img/Product_details_JPG/1121b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (10,'Напитки',1006,'71612-ALOE-VERA-GEL-330ML-12-PACK','Forever Aloe Vera Gel mini','Гел от Алое Вера мини','Със съдържание на над 99,7% чист гел от вътрешността на листата на алое вера Барбаденсис, който се грижи за храносмилателната система. Сега в мини опаковка 12 броя х 330мл!','247.64 лв.','238.12 лв.','235.26 лв.','210.50 лв.','173.35 лв.','https://iglika.me/products_img/Product_details_JPG/1006b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (11,'Напитки',1007,'77812-ALOE-PEACHES-330ML-PACK-OF-12','Forever Aloe Peaches mini','Алое Праскови мини','84,5% чист гел от алое вера, допълнен с натурално пюре и аромат на праскови! Сега в мини опаковка 12 броя х 330мл!','247.64 лв.','238.12 лв.','235.26 лв.','210.50 лв.','173.35 лв.','https://iglika.me/products_img/Product_details_JPG/1007b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (12,'Напитки',1008,'73512-ALOE-BERRY-NECTAR-330ML','Forever Aloe Berry Nectar mini','Алое Бери Нектар мини','90,7% чист гел от алое вера плюс натурални плодови концентрати за подкрепа на вашето здраве! Сега в мини опаковка 12 броя х 330мл!','247.64 лв.','238.12 лв.','235.26 лв.','210.50 лв.','173.35 лв.','https://iglika.me/products_img/Product_details_JPG/1008b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (13,'Напитки',1010,'200-ALOE-BLOSSOM-HERBAL-TEA','Aloe Blossom Herbal Tea','Билков чай с цветчета от Алое','Безкофеинова смес от листа, билки и подправки, която може да се консумира гореща или охладена.','43.06 лв.','40.06 лв.','40.91 лв.','36.60 лв.','30.15 лв.','https://iglika.me/products_img/Product_details_JPG/1010b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (14,'Напитки',1009,'196-FOREVER-FREEDOM','Forever Freedom','Форевър Фрийдъм','Този напитка се гордее с висока концентрация от 89% чист гел от алое вера, който спомага за подкрепата на естествените защитни функции на нашето тяло.','84.61 лв.','81.36 лв.','80.38 лв.','71.92 лв.','59.23 лв.','https://iglika.me/products_img/Product_details_JPG/1009b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (15,'Напитки',1076,'822-FAB-X-ENERGY-DRINK','FAB X Forever Active Boost','ФАБ Х Форевър актив бууст','Поемете контрол върху деня си с ФАБ Х.','8.92 лв.','8.58 лв.','8.48 лв.','7.58 лв.','6.25 лв.','https://iglika.me/products_img/Product_details_JPG/1076b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (16,'Напитки',1011,'821-FAB-ENERGY-DRINK','FAB Forever Active Boost','ФАБ- Енергийна напитка','FAB Forever Active Boost е богат на витамини B2, B3, B6 и B12. Помага за поддържането на нормалната функция на имунната система и намалява умората.','8.92 лв.','8.58 лв.','8.48 лв.','7.58 лв.','6.25 лв.','https://iglika.me/products_img/Product_details_JPG/1011b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (17,'Добавки',1012,'068-FIELDS-OF-GREENS','Fields of Greens','Зелени поля','Fields of Greens е отличен източник на "зелена храна" и антиоксиданти.','28.58 лв.','27.48 лв.','27.15 лв.','24.29 лв.','20.01 лв.','https://iglika.me/products_img/Product_details_JPG/1012b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (18,'Добавки',1078,'672-ABSORBENT-D','Forever Absorbent-D','Абсорбент-Д','Открийте силата на Абсорбент-D – удобна хранителна добавка, доставяща витамин D и вписваща се идеално в натовареното ви ежедневие.','33.91 лв.','32.61 лв.','32.22 лв.','28.83 лв.','23.74 лв.','https://iglika.me/products_img/Product_details_JPG/1078b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (19,'Добавки',1013,'048-ABSORBENT-C','Absorbent-C','Абсорбент-С','Създаден, за да осигури на тялото ви препоръчителната дневна доза на витамин С по лесен и вкусен начин.','41.66 лв.','40.06 лв.','39.58 лв.','35.41 лв.','29.16 лв.','https://iglika.me/products_img/Product_details_JPG/1013b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (20,'Добавки',1014,'376-FOREVER-SUPER-ARCTIC-SEA','Forever Arctic Sea','Арктическо море','Създаден, за да осигури балансирана комбинация от омега-3 мастни киселини.','78.13 лв.','72.68 лв.','74.22 лв.','66.41 лв.','54.69 лв.','https://iglika.me/products_img/Product_details_JPG/1014b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (21,'Добавки',1015,'473-FORVER-ARGI-POUCH','Argi+','Арги','Осигурява на тялото ви L-аргинин, мощна аминокиселина, по удобен и вкусен начин.','163.11 лв.','156.84 лв.','154.96 лв.','138.65 лв.','114.18 лв.','https://iglika.me/products_img/Product_details_JPG/1015b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (22,'Добавки',1016,'188-FOREVER-B-12-PLUS','Forever B12 Plus','Форевър B12 плюс','Форевър B12 плюс е отлична комбинация от витамин В12 и фолиева киселина във формула с постепенно освобождаване.','36.92 лв.','35.50 лв.','35.07 лв.','31.38 лв.','25.84 лв.','https://iglika.me/products_img/Product_details_JPG/1016b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (23,'Добавки',1017,'026-FOREVER-BEE-POLLEN','Forever Bee Pollen','Пчелен прашец','Със съдържание на чист пчелен прашец, комбиниран с мед и пчелно млечице.','36.31 лв.','34.91 лв.','34.49 лв.','30.86 лв.','25.41 лв.','https://iglika.me/products_img/Product_details_JPG/1017b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (24,'Добавки',1018,'027-FOREVER-BEE-PROPOLIS','Forever Bee Propolis','Пчелен прополис','Добавката поддържа защитните сили на организма, съдържа естествени хранителни съединения и е източник на флавоноиди.','75.59 лв.','72.68 лв.','71.81 лв.','64.25 лв.','52.91 лв.','https://iglika.me/products_img/Product_details_JPG/1018b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (25,'Добавки',1026,'036-FOREVER-ROYAL-JELLY','Forever Royal Jelly','Пчелно млечице','Съдържа естествени протеини, мастни киселини, минерални соли, аминокиселини и витамини за подкрепа на здравето.','78.60 лв.','75.58 лв.','74.67 лв.','66.81 лв.','55.02 лв.','https://iglika.me/products_img/Product_details_JPG/1026b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (26,'Добавки',1114,'207-FOREVER-BEE-HONEY','Forever Bee Honey','Пчелен мед','Вкусна съкровищница от ценни природни вещества.','39.89 лв.','38.36 лв.','37.90 лв.','33.91 лв.','27.93 лв.','https://iglika.me/products_img/Product_details_JPG/1114b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (27,'Добавки',1019,'206-FOREVER-CALCIUM','Forever Calcium','Форевър Калций','Създаден за да достави калций, витамин D и да помогне за поддържането на правилното здраве на костите.','57.14 лв.','54.94 лв.','54.28 лв.','48.57 лв.','40.00 лв.','https://iglika.me/products_img/Product_details_JPG/1019b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (28,'Добавки',1020,'065-GARLIC---TYME','Forever Garlic-Thyme','Чесън и мащерка','Съчетава всички ползи от чесъна и мащерката в едно.','43.46 лв.','41.79 лв.','41.29 лв.','36.94 лв.','30.42 лв.','https://iglika.me/products_img/Product_details_JPG/1020b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (29,'Добавки',1021,'355-FOREVER-IMMUBLEND','Forever Immublend','Форевър имубленд','Всестранна хранителна добавка за подкрепа на имунитета с фруктоолигозахариди, лактоферин, гъби маитаке и шийтаке, витамини D, C и цинк.','63.70 лв.','61.25 лв.','60.52 лв.','54.15 лв.','44.59 лв.','https://iglika.me/products_img/Product_details_JPG/1021b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (30,'Добавки',1116,'659-DX-4','DX4™ Body Balancing System','DX4™ балансираща програма','Четиридневна система, която ти помага да рестартираш тялото и ума си!','333.32 лв.','320.50 лв.','316.65 лв.','283.32 лв.','233.32 лв.','https://iglika.me/products_img/Product_details_JPG/1116b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (31,'Добавки',1099,'622-FOREVER-FOCUS','Forever Focus','Форевър фокус','Контролирайте сами деня си с Форевър фокус.','198.83 лв.','191.18 лв.','188.89 лв.','169.00 лв.','139.18 лв.','https://iglika.me/products_img/Product_details_JPG/1099b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (32,'Добавки',1100,'551-FOREVER-MOVE','Forever Move','Форевър мув','Движете се свободно и подкрепяйте подвижността на ставите си!','148.82 лв.','143.10 лв.','141.38 лв.','126.50 лв.','104.18 лв.','https://iglika.me/products_img/Product_details_JPG/1100b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (33,'Добавки',1101,'610-FOREVER-ACTIV-PRO-B','Forever Active Pro-B','Форевър актив про-Б','Балансирана патентована комбинация от шест клинично проучени пробиотични щама.','87.48 лв.','84.12 лв.','83.11 лв.','74.36 лв.','61.24 лв.','https://iglika.me/products_img/Product_details_JPG/1101b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (34,'Добавки',1102,'354-FOREVER-KIDS','Forever Kids','Форевър кидс','Дъвчащи таблетки с витамини и минерали.','33.35 лв.','32.07 лв.','31.69 лв.','28.35 лв.','23.35 лв.','https://iglika.me/products_img/Product_details_JPG/1102b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (35,'Добавки',1103,'439-FOREVER-DAILY','Forever Daily','Форевър дейли','Mултивитамин с възможно най-съвременната система за ефикасно усвояване на съставките.','49.43 лв.','47.53 лв.','46.96 лв.','42.02 лв.','34.60 лв.','https://iglika.me/products_img/Product_details_JPG/1103b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (36,'Добавки',1104,'037-NATURE-MIN','Nature-Min','Нейчър-мин','Форевър нейчър-мин съдържа над 10 незаменими минерали и микроелементи, извлечени от естествена утайка от морското дъно и морски растения.','43.46 лв.','41.79 лв.','41.29 лв.','36.94 лв.','30.42 лв.','https://iglika.me/products_img/Product_details_JPG/1104b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (37,'Добавки',1105,'072-FOREVER-LYCIUM-PLUS','Forever Lycium Plus','Форевър лициум плюс','По-известен като годжи бери, лициумът е древен китайски „ин тоник“ и много силен антиоксидант.','78.60 лв.','75.58 лв.','74.67 лв.','66.81 лв.','55.02 лв.','https://iglika.me/products_img/Product_details_JPG/1105b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (38,'Добавки',1085,'676-FOREVER-TURM','Forever AloeTurm','Форевър АЛОЕТУРМ','Хидрогелни пастили със свеж вкус на мента, които бавно се разтварят в устата ви и доставят куркума, алое вера и цинк.','15.50 лв.','14.90 лв.','14.72 лв.','13.17 лв.','10.85 лв.','https://iglika.me/products_img/Product_details_JPG/1085b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (39,'Добавки',1122,'67610-FOREVER-TURM-10-PACK','Forever AloeTurm 10-pack','Форевър АЛОЕТУРМ пакет от 10бр.','Изгоден пакет от 10 опаковки АЛОЕТУРМ.','147.00 лв.','147.00 лв.','139.65 лв.','124.95 лв.','102.90 лв.','https://iglika.me/products_img/Product_details_JPG/1122b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (40,'Добавки',1022,'566-FOREVER-IMMUNE-GUMMY','Forever Immune Gummy','Форевър имуно гъми','Желирани бонбони с тропически вкус, които осигуряват комбинация от 10 витамина и цинк дневно.','88.08 лв.','84.69 лв.','83.67 лв.','74.87 лв.','61.65 лв.','https://iglika.me/products_img/Product_details_JPG/1022b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (41,'Добавки',1023,'624-FOREVER-IVISION','Forever iVision','Форевър Айвижън','Съдържа комбинация от антиоксиданти и други хранителни вещества, които се грижат за поддържане оптималното здраве на очите.','86.13 лв.','80.12 лв.','81.82 лв.','73.21 лв.','60.29 лв.','https://iglika.me/products_img/Product_details_JPG/1023b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (42,'Добавки',1097,'312-FOREVER-CARDIOHEALTH','Forever CardioHealth','Форевър кардио здраве','Отлична хранителна добавка с коензим Q10 и специална прахообразна формула, създадена за разтваряне в гела от алое на Форевър.','73.83 лв.','68.68 лв.','70.14 лв.','62.76 лв.','51.68 лв.','https://iglika.me/products_img/Product_details_JPG/1097b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (43,'Добавки',1098,'264-FOREVER-ACTIVE-HA','Forever Active HA','Форевър активна ХК','Уникална форма на хиалуронова киселина с ниско молекулярно тегло.','72.04 лв.','69.27 лв.','68.44 лв.','61.23 лв.','50.43 лв.','https://iglika.me/products_img/Product_details_JPG/1098b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (44,'Добавки',1024,'613-FOREVER-MARINE-COLLAGEN','Forever Marine Collagen','Форевър Морски колаген','Висококачествен морски колаген,  полезен за хидратацията на кожата, структурата и здравето и.','194.63 лв.','187.14 лв.','184.89 лв.','165.43 лв.','136.24 лв.','https://iglika.me/products_img/Product_details_JPG/1024b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (45,'Добавки',1025,'215-FOREVER-MULTI-MACA','Forever Multi-Maca','Форевър Mулти-мака','Включва внимателно подбрана смес от корени, плодове и ензими.','63.11 лв.','60.68 лв.','59.95 лв.','53.64 лв.','44.18 лв.','https://iglika.me/products_img/Product_details_JPG/1025b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (46,'Добавки',1028,'374-VITOLIZE-MEN','Vitolize men','Витолайз за него','Съдържа комбинация от билки, витамини, минерали включително цинк.','73.83 лв.','68.68 лв.','70.14 лв.','62.76 лв.','51.68 лв.','https://iglika.me/products_img/Product_details_JPG/1028b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (47,'Добавки',1029,'375-VITOLIZE-WOMEN','Vitolize women','Витолайз за нея','Богата на желязо, което допринася за нормалната когнитивна функция и фолиева киселина.','75.59 лв.','72.68 лв.','71.81 лв.','64.25 лв.','52.91 лв.','https://iglika.me/products_img/Product_details_JPG/1029b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (48,'Добавки',1030,'556-INFINITE-FIRMING-COMPLEX','Infinite by Forever firming complex','Стягащ комплекс','Със съдържание на витамин C, който помага за здравословната формация на колаген в кожата, биотин за поддържане на здрава коса и кожа, и допълнителен морски колаген.','123.20 лв.','118.46 лв.','117.04 лв.','104.72 лв.','86.24 лв.','https://iglika.me/products_img/Product_details_JPG/1030b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (49,'Грижа за лицето',1123,'673-LOGIC-KIT','Logic by Forever Skincare Kit','Лоджик от Форевър','Идеална за всеки тип кожа и особено за смесена. Чудесна за създаване на нов ежедневен режим. Отстъпка при покупка на трите продукта в комплект!','163.56 лв.',NULL,'155.38 лв.','139.03 лв.','114.49 лв.','https://iglika.me/products_img/Product_details_JPG/1123b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (50,'Грижа за лицето',1124,'668-LOGIC-GEL-BALANCING-ESSENCE','Logic by Forever Balancing Aloe Essence','Балансираща алое есенция „Лоджик“','Спомага за хидратацията и възстановяването на равновесието в кожата с над 98% съставки от натурален произход.','57.13 лв.',NULL,'54.27 лв.','48.56 лв.','39.99 лв.','https://iglika.me/products_img/Product_details_JPG/1124b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (51,'Грижа за лицето',1125,'667-LOGIC-ALOE-GEL-CLEANSER','Logic by Forever Aloe Gel Cleanser','Почистващ алое гел „Лоджик“','Нежен, но ефикасен подходящ за всички типове кожа! Съдържа над 96% съставки от натурален произход.','59.51 лв.',NULL,'56.53 лв.','50.58 лв.','41.66 лв.','https://iglika.me/products_img/Product_details_JPG/1125b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (52,'Грижа за лицето',1126,'669-LOGIC-ALOE-SOOTHING-GEL-MOISTU','Logic by Forever Soothing Gel Moisturizer','Успокояващ овлажняващ гел „Лоджик“','Успокояващият овлажняващ гел. Хидратира кожата с над 94% съставки от натурален произход.','63.11 лв.',NULL,'59.95 лв.','53.64 лв.','44.18 лв.','https://iglika.me/products_img/Product_details_JPG/1126b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (53,'Грижа за лицето',1127,'701-VITAMIN-C-AND-BAKUCHIOL-COMBO','Forever Vitamin C™ and Forever Bakuchiol™ Duo','Изсветляващо и подхранващо мляко за лице Форевър витамин C и Форевър бакучиол','Подкрепяйте кожата си от изгрев до залез с дуета за дневна и нощна грижа - Форевър витамин С и Форевър бакучиол.','223.13 лв.',NULL,'211.97 лв.','189.66 лв.','156.19 лв.','https://iglika.me/products_img/Product_details_JPG/1127b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (54,'Грижа за лицето',1128,'686-FOREVER-VITAMIN-C','Forever Vitamin C™ Brightening Facial Milk','Изсветляващото мляко за лице Форевър витамин С','Избистря цвета на кожата с концентрация от 6% клинично тестван витамин C!','117.52 лв.',NULL,'111.64 лв.','99.89 лв.','82.26 лв.','https://iglika.me/products_img/Product_details_JPG/1128b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (55,'Грижа за лицето',1129,'687-FOREVER-BAKUCHIOL','Forever Bakuchiol™ Nourishing Facial Milk','Подхранващото мляко за лице Форевър бакучиол','Допринася за намаляване на видимите признаци на стареене с 1% бакучиол!','117.52 лв.',NULL,'111.64 лв.','99.89 лв.','82.26 лв.','https://iglika.me/products_img/Product_details_JPG/1129b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (56,'Грижа за лицето',1031,'612-ALOE-ACTIVATOR-2018','Aloe activator','Алое активатор','Този продукт съдържа над 98% гел от алое вера, което го прави идеален за чувствителна кожа.','39.36 лв.','36.61 лв.','37.39 лв.','33.45 лв.','27.55 лв.','https://iglika.me/products_img/Product_details_JPG/1031b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (57,'Грижа за лицето',1032,'561-AWAKENING-EYE-CREAM','Awakening eye cream','Пробуждащ околоочен крем','Предназначен да подобри и изглади чувствителната област около очите, видимо намалява появата на линии, бръчки и тъмни кръгове.','43.46 лв.','41.79 лв.','41.29 лв.','36.94 лв.','30.42 лв.','https://iglika.me/products_img/Product_details_JPG/1032b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (58,'Грижа за лицето',1033,'560-BALANCING-TONER','Balancing toner','Балансиращ тоник','Помага да се балансира pH на кожата и да се премахне излишният остатък след използване на почистващи продукти.','51.77 лв.','49.78 лв.','49.18 лв.','44.01 лв.','36.24 лв.','https://iglika.me/products_img/Product_details_JPG/1033b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (59,'Грижа за лицето',1077,'664-FOREVER-BIO-CELLULOSE-MASK-X3','Aloe Bio-Cellulose Mask','Алое био-целуозна маска','Алое био-целулозната маска на Форевър осигурява интензивно и съживяващо овлажняване с напредничави технологии и натурални съставки.','75.59 лв.','72.68 лв.','71.81 лв.','64.25 лв.','52.91 лв.','https://iglika.me/products_img/Product_details_JPG/1077b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (60,'Грижа за лицето',1034,'022-ALOE-LIPS-','Aloe lips','Алое липс','Най-доброто решение срещу напукани устни.','8.32 лв.','8.00 лв.','7.90 лв.','7.07 лв.','5.82 лв.','https://iglika.me/products_img/Product_details_JPG/1034b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (61,'Грижа за лицето',1035,'238-FOREVER-ALOE-SCRUB','Aloe scrub','Алое ексфолиант','Натурален ексфолиант за лице и тяло.','37.52 лв.','36.08 лв.','35.65 лв.','31.89 лв.','26.27 лв.','https://iglika.me/products_img/Product_details_JPG/1035b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (62,'Грижа за лицето',1036,'553-INFINITE-SKIN-CARE-KIT','Infinite by Forever','Инфинит от Форевър','Продуктите се грижат за това да намалят появата на фини линии и бръчки, да подобрят гладкостта на кожата и да подкрепят красотата отвътре навън.','416.67 лв.','400.64 лв.','395.83 лв.','354.17 лв.','291.67 лв.','https://iglika.me/products_img/Product_details_JPG/1036b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (63,'Грижа за лицето',1037,'618-HYDRATING-SERUM','Hydrating serum','Хидратиращ серум','Продукт за грижа за кожата, предназначен да осигури максимална хидратация.','83.32 лв.','80.12 лв.','79.16 лв.','70.83 лв.','58.33 лв.','https://iglika.me/products_img/Product_details_JPG/1037b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (64,'Грижа за лицето',1038,'555-INFINITE-FIRMING-SERUM','Infinite by Forever firming serum','Инфинит стягащ серум','Допълва естествените процеси в кожата, за да увеличи здравината и да намали появата на фини линии и бръчки','123.81 лв.','119.05 лв.','117.62 лв.','105.24 лв.','86.67 лв.','https://iglika.me/products_img/Product_details_JPG/1038b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (65,'Грижа за лицето',1039,'554-INFINITE-HYDRATING-CLEANSER','Infinite by Forever hydrating cleanser','Хидратиращ почистващ лосион','Хидратира кожата, нежно отмива мръсотията и мазнините без да изсушава.','62.51 лв.','60.11 лв.','59.39 лв.','53.14 лв.','43.76 лв.','https://iglika.me/products_img/Product_details_JPG/1039b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (66,'Грижа за лицето',1040,'558-INFINITE-RESTORING-CREAM','Infinite by Forever restoring creme','Възстановяващ крем','Абсорбира се в кожата, като я оставя хидратирана и гладка.','138.08 лв.','132.77 лв.','131.18 лв.','117.37 лв.','96.66 лв.','https://iglika.me/products_img/Product_details_JPG/1040b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (67,'Грижа за лицето',1106,'653-REPLENISHING-SKIN-OIL','Replenishing Skin Oil','Възобновяващо масло за лице','Възобновяващото масло за лице е лека течност без силикони.','72.04 лв.','69.27 лв.','68.44 лв.','61.23 лв.','50.43 лв.','https://iglika.me/products_img/Product_details_JPG/1106b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (68,'Грижа за лицето',1107,'651-DEEP-MOISTURIZING-CREAM','Deep moisturizing cream','Дълбоко овлажняващ крем','Някои хидратанти са като капка вода. Този крем е като цял басейн.','79.18 лв.','76.13 лв.','75.22 лв.','67.30 лв.','55.42 лв.','https://iglika.me/products_img/Product_details_JPG/1107b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (69,'Грижа за лицето',1108,'069-R3-FACTOR-SKIN-CREME','R3 Factor','R3 фактор','Съхранете, възстановете и обновете.','78.60 лв.','75.58 лв.','74.67 лв.','66.81 лв.','55.02 лв.','https://iglika.me/products_img/Product_details_JPG/1108b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (70,'Грижа за лицето',1109,'341-MASK-POWDER','Mask Powder','Маска за лице','Стяга и почиства порите ви в дълбочина.','45.23 лв.','43.49 лв.','42.97 лв.','38.45 лв.','31.66 лв.','https://iglika.me/products_img/Product_details_JPG/1109b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (71,'Грижа за лицето',1041,'645-PROTECTING-DAY-LOTION','Protecting Day Lotion','Защитен дневен лосион','Този лосион предлага широкоспектърна SPF 20 защита и подхранва кожата.','86.91 лв.','83.57 лв.','82.57 лв.','73.88 лв.','60.84 лв.','https://iglika.me/products_img/Product_details_JPG/1041b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (72,'Грижа за лицето',1042,'559-SMOOTHING-EXFOLIATOR','Smoothing exfoliator','Изглаждащ ексфолиант','Премахва мъртвите клетки и изглажда текстурата, за по-сияеща кожа.','43.46 лв.','41.79 лв.','41.29 лв.','36.94 лв.','30.42 лв.','https://iglika.me/products_img/Product_details_JPG/1042b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (73,'Грижа за тялото',1048,'647-ALOE-BODY-LOTION','Aloe Body Lotion','Алое лосион за тяло','Ежедневен овлажняващ продукт, който омекотява кожата и я оставя хидратирана и здрава.','54.12 лв.','52.04 лв.','51.42 лв.','46.00 лв.','37.89 лв.','https://iglika.me/products_img/Product_details_JPG/1048b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (74,'Грижа за тялото',1049,'564-ALOE-COOLING-LOTION','Aloe Cooling lotion','Aлое oхлаждащ лосион','Предоставя охлаждащо усещане с освежаващ ментов аромат.','35.71 лв.','34.34 лв.','33.93 лв.','30.36 лв.','25.00 лв.','https://iglika.me/products_img/Product_details_JPG/1049b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (75,'Грижа за тялото',1050,'040-ALOE-FIRST-SPRAY','Aloe First','Алое Фърст','Успокояващ продукт за грижа за кожата, съдържащ гел от алое вера, пчелен прополис и единадесет полезни билкови екстракта.','47.05 лв.','45.24 лв.','44.70 лв.','39.99 лв.','32.93 лв.','https://iglika.me/products_img/Product_details_JPG/1050b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (76,'Грижа за тялото',1051,'205-ALOE-MSM-GEL','Aloe MSM Gel','Алое МСМ гел','Предназначен за облекчаване на ставни и мускулни болки.','54.79 лв.','52.68 лв.','52.05 лв.','46.57 лв.','38.35 лв.','https://iglika.me/products_img/Product_details_JPG/1051b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (77,'Грижа за тялото',1052,'051-ALOE-PROPOLIS-CREME','Aloe Propolis Creme','Алое Прополис крем','Витамините A, E и C работят за подхранване и овлажняване на кожата, докато прополисът помага за подмладяване на кожата.','47.05 лв.','45.24 лв.','44.70 лв.','39.99 лв.','32.93 лв.','https://iglika.me/products_img/Product_details_JPG/1052b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (78,'Грижа за тялото',1110,'063-ALOE-MOISTURIZING-LOTION','Aloe Moisturizing Lotion','Овлажняващ алое лосион','Съдържа 100% стабилизиран гел от алое вера, алантоин, масло от кайсиеви ядки, масло от жожоба.','35.71 лв.','34.34 лв.','33.93 лв.','30.36 лв.','25.00 лв.','https://iglika.me/products_img/Product_details_JPG/1110b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (79,'Грижа за тялото',1053,'617-SUNSCREEN-LOTION-MIT-FREE','Aloe sunscreen','Алое Сънскрийн','Този слънцезащитен продукт предлага водоустойчива SPF 30 защита от UVA и UVB лъчи, плюс успокояващата сила на алое.','49.43 лв.','47.53 лв.','46.96 лв.','42.02 лв.','34.60 лв.','https://iglika.me/products_img/Product_details_JPG/1053b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (80,'Грижа за тялото',1054,'061-ALOE-VERA-GELLY','Aloe Vera Gelly','Алое Вера гел Джели','Почти идентичен с вътрешността на листата на алое вера, овлажнява, подхранва и успокоява кожата','35.71 лв.','34.34 лв.','33.93 лв.','30.36 лв.','25.00 лв.','https://iglika.me/products_img/Product_details_JPG/1054b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (81,'Лична хигиена',1055,'284-AVOCADO-SOAP','Aloe Avocado Face & Body Soap','Алое и авокадо сапун за лице и тяло','Достатъчно нежен за цялото ви тяло и лице с аромат на свежо набрани цитрусови плодове.','14.31 лв.','13.76 лв.','13.59 лв.','12.16 лв.','10.02 лв.','https://iglika.me/products_img/Product_details_JPG/1055b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (82,'Лична хигиена',1079,'644-MALOSI-MENS-COLOGNE','Forever Malosi Fine Frangrance for Him','Парфюм "Малоси" за него','Обгърнете сетивата си със силата на любовта на островите Самоа с помощта на този изключителен фин парфюм, който отдава почит към основателя на Форевър Рекс Моън и неговата дълбока връзка с народа на Самоа.','79.76 лв.','76.69 лв.','75.77 лв.','67.79 лв.','55.83 лв.','https://iglika.me/products_img/Product_details_JPG/1079b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (83,'Лична хигиена',1080,'643-ALOFA-WOMENS-PERFUME','Forever Alofa Fine Frangrance for Her','Парфюм "Алофа" за нея','Обгърнете сетивата си със силата на любовта на островите Самоа с помощта на този изключителен фин парфюм, който отдава почит към основателя на Форевър Рекс Моън и неговата дълбока връзка с народа на Самоа.','79.76 лв.','76.69 лв.','75.77 лв.','67.79 лв.','55.83 лв.','https://iglika.me/products_img/Product_details_JPG/1080b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (84,'Лична хигиена',1081,'642-NOURISHING-HAIR-OIL','Nourishing Hair Oil','Подхранващо масло за коса','Шест растителни масла без силикони предлагат хидратация и подхранване.','66.06 лв.','63.52 лв.','62.76 лв.','56.15 лв.','46.24 лв.','https://iglika.me/products_img/Product_details_JPG/1081b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (85,'Лична хигиена',1115,'067-ALOE-EVER-SHIELD-DEODORANT','Aloe Ever-Shield Deodorant Stick','Сух алое дезодорант','Нежната формула със стабилизиран гел от алое вера не съдържа вредни алуминиеви соли.','17.26 лв.','16.60 лв.','16.40 лв.','14.67 лв.','12.08 лв.','https://iglika.me/products_img/Product_details_JPG/1115b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (86,'Лична хигиена',1056,'646-ALOE-BODY-WASH','Aloe Body Wash','Алое Душ-гел','Формула без сулфати предлага мощно, но нежно почистване със съставки които подхранват кожата, отмиват мръсотията и я оставят мека и освежена.','53.55 лв.','51.49 лв.','50.87 лв.','45.52 лв.','37.48 лв.','https://iglika.me/products_img/Product_details_JPG/1056b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (87,'Лична хигиена',1057,'633-ALOE-LIQUID-SOAP-','Aloe Liquid Soap','Алое течен сапун','Овлажнява и почиства, оставяйки кожата ви по-мека, по-гладка и по-сияйна.','44.64 лв.','42.92 лв.','42.40 лв.','37.94 лв.','31.25 лв.','https://iglika.me/products_img/Product_details_JPG/1057b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (88,'Лична хигиена',1058,'640-ALOE-JOJOBA-SHAMPOO','Aloe-Jojoba Shampoo','Алое-жожоба шампоан','Направен с чист алое вера гел и укрепващо жожоба масло, този шампоан е перфектен за ежедневна употреба,','51.77 лв.','49.78 лв.','49.18 лв.','44.01 лв.','36.24 лв.','https://iglika.me/products_img/Product_details_JPG/1058b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (89,'Лична хигиена',1059,'641-ALOE-JOJOBA-CONDITIONER','Aloe-Jojoba Conditioner','Алое-жожоба балсам','Подхранва и хидратира в дълбочина, като омекотява, изглажда и прави косата по-лесна за разресване.','55.38 лв.','53.25 лв.','52.61 лв.','47.07 лв.','38.77 лв.','https://iglika.me/products_img/Product_details_JPG/1059b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (90,'Лична хигиена',1060,'028-FOREVER-BRIGHT-TOOTH-GEL','Forever Bright Toothgel','Гел за зъби Форевър брайт','Формулата без флуорид оставя след себе си усещане за свежест и чистота.','18.45 лв.','17.74 лв.','17.53 лв.','15.68 лв.','12.91 лв.','https://iglika.me/products_img/Product_details_JPG/1060b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (91,'Лична хигиена',1061,'070-GENTLEMANS-PRIDE-AFTERSHAVE','Gentleman’s Pride After Shave Balm','Балсам за след бръснене','Предлага ексклузивна комбинация от съставки, които осигуряват охлаждащо усещане и прекрасен аромат.','35.71 лв.','34.34 лв.','33.93 лв.','30.36 лв.','25.00 лв.','https://iglika.me/products_img/Product_details_JPG/1061b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (92,'Пакети',1063,'001-A-TOUCH-OF-FOREVER','Touch of Forever','Докосване до Форевър','Троен пакет Гел от Алое Вера!','1,160.99 лв.','1,116.34 лв.','1,102.94 лв.','986.84 лв.','812.70 лв.','https://iglika.me/products_img/Product_details_JPG/1063b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (93,'Пакети',1064,'71633-ARGI-AND-ALOE-MINI-TRIPACK','ARGI+ & Aloe Mini TriPak','ТриПак АРГИ+ и Алое мини','Троен пакет Алое Праскова!','78.20 лв.','75.19 лв.','74.29 лв.','66.47 лв.','54.74 лв.','https://iglika.me/products_img/Product_details_JPG/1064b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (94,'Пакети',1083,'456-VITAL-5','Vital5/Aloe Vera Gel','Витал 5/Алое Вера гел','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','577.76 лв.','555.54 лв.','548.87 лв.','491.10 лв.','404.43 лв.','https://iglika.me/products_img/Product_details_JPG/1083b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (95,'Пакети',1096,'457-VITAL-5-BERRY','Vital5/Aloe Berry Nectar','Витал 5/Алое Бери нектар','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','577.76 лв.','555.54 лв.','548.87 лв.','491.10 лв.','404.43 лв.','https://iglika.me/products_img/Product_details_JPG/1096b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (96,'Пакети',1074,'529-F15-BEGINNER-12-CHOCOLATE','F15 Beginner/Chocolate','Ф15 Начинаещи/Шоколад','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1074b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (97,'Пакети',1086,'528-F15-BEGINNER-12-VANILLA','F15 Beginner/Vanilla','Ф15 Начинаещи/Ванилия','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1086b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (98,'Пакети',1087,'533-F15-INTEBEGINNER-12-CHOCOLATE','F15 Intermediate/Chocolate','Ф15 Средно напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1074b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (99,'Пакети',1088,'532-F15-INTERMEDIATE-12-VANILLA','F15 Intermediate/Vanilla','Ф15 Средно напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1086b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (100,'Пакети',1089,'537-F15-ADVANCED-12-CHOCOLATE','F15 Advanced/Chocolate','Ф15 Напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1074b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (101,'Пакети',1090,'536-F15-ADVANCED-12-VANILLA','F15 Advanced/Vanilla','Ф15 Напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1086b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (102,'Пакети',1073,'475-C9-GEL-VANILLA','Clean-9/Gel-Vanilla','Клийн-9/Алое Вера гел-Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1073b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (103,'Пакети',1091,'476-C9-GEL-CHOCOLATE','Clean-9/Gel-Chocolate','Клийн-9/Алое Вера гел-Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1091b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (104,'Пакети',1092,'625-C9-BERRY-VANILLA','Clean-9/Berry-Vanilla','Клийн-9/Алое Бери нектар-Ванилия','Пакет от популярни продукти от Forever Living Products, предназначени да ви запознаят с предложенията на марката.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1092b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (105,'Пакети',1093,'626-C9-BERRY-CHOCOLATE','Clean-9/Berry-Chocolate','Клийн-9/Алое Бери нектар-Шоколад','Ако търсите начин да започнете собствен Форевър бизнес или да пазарувате продуктите на Форевър Ливинг с 30% отстъпка, този пакет може да ви заинтригува.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1093b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (106,'Пакети',1094,'629-C9-PEACH-VANILLA','Clean-9/Peach-Vanilla','Клийн-9/Алое Праскова-Ванилия','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен ванилов вкус.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1094b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (107,'Пакети',1095,'630-C9-PEACH-CHOCOLATE','Clean-9/Peach-Chocolate','Клийн-9/Алое Праскова-Шоколад','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен шоколадов вкус.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1095b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (108,'Контрол на теглото',1066,'471-FOREVER-LITE-ULTRA-CHOCOLAT-15','Forever Lite Ultra with Aminotein chocolate','Форевър лайт ултра с аминотеин шоколад','В пакета получавате ГЕЛА ОТ АЛОЕ ВЕРА заедно с АЛОЕ И ПРАСКОВИ и АЛОЕ БЕРИ НЕКТАР с неговия свеж и богат на антиоксиданти вкус, подкрепящ нормалното храносмилане.','59.52 лв.','57.23 лв.','56.54 лв.','50.59 лв.','41.66 лв.','https://iglika.me/products_img/Product_details_JPG/1066b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (109,'Контрол на теглото',1067,'470-FOREVER-LITE-ULTRA-VANILLA-15','Forever Lite Ultra with Aminotein vanilla','Форевър лайт ултра с аминотеин ванилия','В пакета ще откриете три мини опаковки гел от алое вера по 330 мл и три пакетчета Арги+.','59.52 лв.','57.23 лв.','56.54 лв.','50.59 лв.','41.66 лв.','https://iglika.me/products_img/Product_details_JPG/1067b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (110,'Контрол на теглото',1068,'656-FOREVER-PLANT-PROTEIN-POUCH','Forever Plant Protein','Форевър Растителен протеин','Четиридневна програма, която помага за рестартиране на вашето физическо, ментално и духовно здраве чрез седем хранителни продукта, практики за установяване на мисленето и ръководство за приемане на храната.','132.72 лв.','127.62 лв.','126.09 лв.','112.82 лв.','92.91 лв.','https://iglika.me/products_img/Product_details_JPG/1068b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (111,'Контрол на теглото',1069,'665-FOREVER-SENSATIABLE','Forever Sensatiable','Форевър Сенсейшабъл','Програма Vital5 е нашето решение за пълноценно хранене в един удобен пакет.','62.51 лв.','60.11 лв.','59.39 лв.','53.14 лв.','43.76 лв.','https://iglika.me/products_img/Product_details_JPG/1069b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (112,'Контрол на теглото',1070,'289-FOREVER-LEAN','Forever Lean','Форевър Лийн','Програма Vital5 е нашето решение за пълноценно хранене в един удобен пакет.','89.90 лв.','86.44 лв.','85.40 лв.','76.41 лв.','62.93 лв.','https://iglika.me/products_img/Product_details_JPG/1070b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (113,'Контрол на теглото',1071,'520-FAST-BREAK-BARS','Forever FastBreak','Форевър Фаст Брейк','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','10.72 лв.','10.31 лв.','10.19 лв.','9.11 лв.','7.51 лв.','https://iglika.me/products_img/Product_details_JPG/1071b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (114,'Контрол на теглото',1111,'463-FOREVER-THERM','Forever Therm','Форевър терм','Зелен чай, гуарана и натурален кофеин ви зареждат с енергия и стимулират метаболизма ви.','82.72 лв.','79.54 лв.','78.59 лв.','70.31 лв.','57.91 лв.','https://iglika.me/products_img/Product_details_JPG/1111b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (115,'Контрол на теглото',1112,'071-GARCINIA-PLUS','Forever Garcinia Plus','Форевър гарциния плюс','Възпрепятства преобразуването на въглехидратите в мастни тъкани.','78.60 лв.','75.58 лв.','74.67 лв.','66.81 лв.','55.02 лв.','https://iglika.me/products_img/Product_details_JPG/1112b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (116,'Контрол на теглото',1113,'464-FOREVER-FIBER-30','Forever Fiber','Форевър фибри','Лесно добавяйте фибри към всекидневния си режим с нашите удобни пакетчета.','55.37 лв.','51.51 лв.','52.60 лв.','47.07 лв.','38.76 лв.','https://iglika.me/products_img/Product_details_JPG/1113b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (117,'Контрол на теглото',1074,'529-F15-BEGINNER-12-CHOCOLATE','F15 Beginner/Chocolate','Ф15 Начинаещи/Шоколад','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1074b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (118,'Контрол на теглото',1086,'528-F15-BEGINNER-12-VANILLA','F15 Beginner/Vanilla','Ф15 Начинаещи/Ванилия','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1086b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (119,'Контрол на теглото',1087,'533-F15-INTEBEGINNER-12-CHOCOLATE','F15 Intermediate/Chocolate','Ф15 Средно напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1074b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (120,'Контрол на теглото',1088,'532-F15-INTERMEDIATE-12-VANILLA','F15 Intermediate/Vanilla','Ф15 Средно напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1086b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (121,'Контрол на теглото',1089,'537-F15-ADVANCED-12-CHOCOLATE','F15 Advanced/Chocolate','Ф15 Напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1074b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (122,'Контрол на теглото',1090,'536-F15-ADVANCED-12-VANILLA','F15 Advanced/Vanilla','Ф15 Напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','350.81 лв.','337.32 лв.','333.27 лв.','298.19 лв.','245.57 лв.','https://iglika.me/products_img/Product_details_JPG/1086b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (123,'Контрол на теглото',1073,'475-C9-GEL-VANILLA','Clean-9/Gel-Vanilla','Клийн-9/Алое Вера гел-Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1073b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (124,'Контрол на теглото',1091,'476-C9-GEL-CHOCOLATE','Clean-9/Gel-Chocolate','Клийн-9/Алое Вера гел-Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1091b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (125,'Контрол на теглото',1092,'625-C9-BERRY-VANILLA','Clean-9/Berry-Vanilla','Клийн-9/Алое Бери нектар-Ванилия','Пакет от популярни продукти от Forever Living Products, предназначени да ви запознаят с предложенията на марката.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1092b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (126,'Контрол на теглото',1093,'626-C9-BERRY-CHOCOLATE','Clean-9/Berry-Chocolate','Клийн-9/Алое Бери нектар-Шоколад','Ако търсите начин да започнете собствен Форевър бизнес или да пазарувате продуктите на Форевър Ливинг с 30% отстъпка, този пакет може да ви заинтригува.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1093b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (127,'Контрол на теглото',1094,'629-C9-PEACH-VANILLA','Clean-9/Peach-Vanilla','Клийн-9/Алое Праскова-Ванилия','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен ванилов вкус.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1094b.jpg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,price_old,discount5,discount15,discount30,image3) VALUES (128,'Контрол на теглото',1095,'630-C9-PEACH-CHOCOLATE','Clean-9/Peach-Chocolate','Клийн-9/Алое Праскова-Шоколад','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен шоколадов вкус.','281.13 лв.','270.32 лв.','267.08 лв.','238.96 лв.','196.79 лв.','https://iglika.me/products_img/Product_details_JPG/1095b.jpg');
