USE products;

CREATE TABLE forever_table(
   amount_p          INTEGER  NOT NULL PRIMARY KEY 
  ,category          VARCHAR(18) NOT NULL
  ,id                INTEGER  NOT NULL
  ,forever_name      VARCHAR(35)
  ,h1                VARCHAR(43) NOT NULL
  ,h2                VARCHAR(38) NOT NULL
  ,description       VARCHAR(206)
  ,price             VARCHAR(12) NOT NULL
  ,discount15        VARCHAR(10) NOT NULL
  ,discount30        VARCHAR(10) NOT NULL
  ,url               VARCHAR(9) NOT NULL
  ,image3            VARCHAR(60) NOT NULL
  ,forever_url_Rumen VARCHAR(35)
);
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (1,'Напитки',1000,'815-ALOE-VERA-GEL','Forever Aloe Vera Gel','Гел от Алое Вера','Със съдържание на над 99,7% чист гел от вътрешността на листата на алое вера Барбаденсис, който се грижи за храносмилателната система.','59.54 лв.','50.61 лв.','41.68 лв.','1000.html','https://iglika.me/products_img/Product_details_JPG/1000b.jpg','https://thealoeveraco.shop/MVdz18Km');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (2,'Напитки',1001,'836-FOREVER-ALOE-MANGO','Forever Aloe Mango','Алое Манго','Подкрепете храносмилателната си система с 86% чисто алое вера и манго вкус!','59.54 лв.','50.61 лв.','41.68 лв.','1001.html','https://iglika.me/products_img/Product_details_JPG/1001b.jpg','https://thealoeveraco.shop/8YzEnKW4');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (3,'Напитки',1075,'877-ALOE-PEACH','Forever Aloe Peaches','Алое и праскови','Подобрете храносмилането си с 84.5%  чисто алое вера и сочни праскови.','59.54 лв.','50.61 лв.','41.68 лв.','1075.html','https://iglika.me/products_img/Product_details_JPG/1075b.jpg','https://thealoeveraco.shop/ZfyOdxvY');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (4,'Напитки',1002,'834-ALOE-BERRY-NECTAR','Forever Aloe Berry Nectar','Алое Бери Нектар','90,7% чист гел от алое вера плюс натурални плодови концентрати за подкрепа на вашето здраве!','59.54 лв.','50.61 лв.','41.68 лв.','1002.html','https://iglika.me/products_img/Product_details_JPG/1002b.jpg','https://thealoeveraco.shop/NpYCZ0rn');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (5,'Напитки',1003,'8153-TRIPACK-ALOE-VERA-GEL','Aloe Vera Gel TriPack','Гел от Алое Вера ТриПак','Троен пакет Гел от Алое Вера!','178.61 лв.','151.82 лв.','125.03 лв.','1003.html','https://iglika.me/products_img/Product_details_JPG/1003b.jpg','https://thealoeveraco.shop/QKf7H3DK');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (6,'Напитки',1004,'8773-TRIPACK-ALOE-PEACH','Forever Aloe Peach TriPak','Алое Праскова ТриПак','Троен пакет Алое Праскова!','178.61 лв.','151.82 лв.','125.03 лв.','1004.html','https://iglika.me/products_img/Product_details_JPG/1004b.jpg','https://thealoeveraco.shop/KA3yqWyj');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (7,'Напитки',1005,'8343-TRIPACK-ALOE-BERRY-NECTAR','Aloe Berry Nectar TriPak','Алое Бери Нектар ТриПак','Троен пакет Алое Бери нектар!','178.61 лв.','151.82 лв.','125.03 лв.','1005.html','https://iglika.me/products_img/Product_details_JPG/1005b.jpg','https://thealoeveraco.shop/lh6O4vjr');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (8,'Напитки',1084,'8333-TRIPACK-ALOE-COMBO','Aloe Drinks TriPack','ТриПак - алое напитки','В пакета получавате Гел от Алое Вера заедно с Алое и Праскови и Алое Бери Нектар. Свеж и богат на антиоксиданти вкус, подкрепящ нормалното храносмилане.','178.61 лв.','151.82 лв.','125.03 лв.','1084.html','https://iglika.me/products_img/Product_details_JPG/1084b.jpg','https://thealoeveraco.shop/m2owhXTK');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (9,'Напитки',1006,'71612-ALOE-VERA-GEL-330ML-12-PACK','Forever Aloe Vera Gel mini','Гел от Алое Вера мини','Със съдържание на над 99,7% чист гел от вътрешността на листата на алое вера Барбаденсис, който се грижи за храносмилателната система. Сега в мини опаковка 12 броя х 330мл!','238.12 лв.','202.40 лв.','166.68 лв.','1006.html','https://iglika.me/products_img/Product_details_JPG/1006b.jpg','https://thealoeveraco.shop/4RvdUmOy');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (10,'Напитки',1007,'77812-ALOE-PEACHES-330ML-PACK-OF-12','Forever Aloe Peaches mini','Алое Праскови мини','84,5% чист гел от алое вера, допълнен с натурално пюре и аромат на праскови! Сега в мини опаковка 12 броя х 330мл!','238.12 лв.','202.40 лв.','166.68 лв.','1007.html','https://iglika.me/products_img/Product_details_JPG/1007b.jpg','https://thealoeveraco.shop/u1fGIlIO');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (11,'Напитки',1008,'73512-ALOE-BERRY-NECTAR-330ML','Forever Aloe Berry Nectar mini','Алое Бери Нектар мини','90,7% чист гел от алое вера плюс натурални плодови концентрати за подкрепа на вашето здраве! Сега в мини опаковка 12 броя х 330мл!','238.12 лв.','202.40 лв.','166.68 лв.','1008.html','https://iglika.me/products_img/Product_details_JPG/1008b.jpg','https://thealoeveraco.shop/F050J9YB');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (12,'Напитки',1010,'200-ALOE-BLOSSOM-HERBAL-TEA','Aloe Blossom Herbal Tea','Билков чай с цветчета от Алое','Безкофеинова смес от листа, билки и подправки, която може да се консумира гореща или охладена.','40.06 лв.','34.05 лв.','28.04 лв.','1010.html','https://iglika.me/products_img/Product_details_JPG/1010b.jpg','https://thealoeveraco.shop/CoHf1JAe');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (13,'Напитки',1009,'196-FOREVER-FREEDOM','Forever Freedom','Форевър Фрийдъм','Този напитка се гордее с висока концентрация от 89% чист гел от алое вера, който спомага за подкрепата на естествените защитни функции на нашето тяло.','81.36 лв.','69.16 лв.','56.95 лв.','1009.html','https://iglika.me/products_img/Product_details_JPG/1009b.jpg','https://thealoeveraco.shop/4gEsZLz7');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (14,'Напитки',1082,'670-FOREVER-MOR','Forever MOR','Форевър МООР','Форевър МООР е следващата стъпка в еволюцията на сутрешното ви кафе, издигайки го до ново ниво с уникална комбинация от B витамини и таурин.','55.51 лв.','47.18 лв.','38.86 лв.','1082.html','https://iglika.me/products_img/Product_details_JPG/1082b.jpg','https://thealoeveraco.shop/LWYOApb6');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (15,'Напитки',1076,'822-FAB-X-ENERGY-DRINK','FAB X Forever Active Boost','ФАБ Х Форевър актив бууст','Поемете контрол върху деня си с ФАБ Х.','8.58 лв.','7.29 лв.','6.01 лв.','1076.html','https://iglika.me/products_img/Product_details_JPG/1076b.jpg','https://thealoeveraco.shop/6jiYdjhY');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (16,'Напитки',1011,'721-FAB-ENERGY-DRINK','FAB Forever Active Boost','ФАБ- Енергийна напитка','FAB Forever Active Boost е богат на витамини B2, B3, B6 и B12. Помага за поддържането на нормалната функция на имунната система и намалява умората.','8.58 лв.','7.29 лв.','6.01 лв.','1011.html','https://iglika.me/products_img/Product_details_JPG/1011b.jpg','https://thealoeveraco.shop/lI9qE166');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (17,'Добавки',1012,'068-FIELDS-OF-GREENS','Fields of Greens','Зелени поля','Fields of Greens е отличен източник на "зелена храна" и антиоксиданти.','27.48 лв.','23.36 лв.','19.24 лв.','1012.html','https://iglika.me/products_img/Product_details_JPG/1012b.jpg','https://thealoeveraco.shop/DwSQvpU8');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (18,'Добавки',1078,'672-ABSORBENT-D','Forever Absorbent-D','Абсорбент-Д','Открийте силата на Абсорбент-D – удобна хранителна добавка, доставяща витамин D и вписваща се идеално в натовареното ви ежедневие.','32.61 лв.','27.72 лв.','22.83 лв.','1078.html','https://iglika.me/products_img/Product_details_JPG/1078b.jpg','https://thealoeveraco.shop/o6CfTF3U');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (19,'Добавки',1013,'048-ABSORBENT-C','Absorbent-C','Абсорбент-С','Създаден, за да осигури на тялото ви препоръчителната дневна доза на витамин С по лесен и вкусен начин.','40.06 лв.','34.05 лв.','28.04 лв.','1013.html','https://iglika.me/products_img/Product_details_JPG/1013b.jpg','https://thealoeveraco.shop/N3oIaEKt');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (20,'Добавки',1014,'376-FOREVER-SUPER-ARCTIC-SEA','Forever Arctic Sea','Арктическо море','Създаден, за да осигури балансирана комбинация от омега-3 мастни киселини.','72.68 лв.','61.78 лв.','50.88 лв.','1014.html','https://iglika.me/products_img/Product_details_JPG/1014b.jpg','https://thealoeveraco.shop/6poMbxCu');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (21,'Добавки',1015,'473-FORVER-ARGI-POUCH','Argi+','Арги','Осигурява на тялото ви L-аргинин, мощна аминокиселина, по удобен и вкусен начин.','156.84 лв.','133.31 лв.','109.79 лв.','1015.html','https://iglika.me/products_img/Product_details_JPG/1015b.jpg','https://thealoeveraco.shop/j8KpEC9A');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (22,'Добавки',1016,'188-FOREVER-B-12-PLUS','Forever B12 Plus','Форевър B12 плюс','Форевър B12 плюс е отлична комбинация от витамин В12 и фолиева киселина във формула с постепенно освобождаване.','35.50 лв.','30.18 лв.','24.85 лв.','1016.html','https://iglika.me/products_img/Product_details_JPG/1016b.jpg','https://thealoeveraco.shop/NIm8bMsN');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (23,'Добавки',1017,'026-FOREVER-BEE-POLLEN','Forever Bee Pollen','Пчелен прашец','Със съдържание на чист пчелен прашец, комбиниран с мед и пчелно млечице.','34.91 лв.','29.67 лв.','24.44 лв.','1017.html','https://iglika.me/products_img/Product_details_JPG/1017b.jpg','https://thealoeveraco.shop/8aXa6pM6');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (24,'Добавки',1018,'027-FOREVER-BEE-PROPOLIS','Forever Bee Propolis','Пчелен прополис','Добавката поддържа защитните сили на организма, съдържа естествени хранителни съединения и е източник на флавоноиди.','72.68 лв.','61.78 лв.','50.88 лв.','1018.html','https://iglika.me/products_img/Product_details_JPG/1018b.jpg','https://thealoeveraco.shop/15Dx7TdM');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (25,'Добавки',1026,'036-FOREVER-ROYAL-JELLY','Forever Royal Jelly','Пчелно млечице','Съдържа естествени протеини, мастни киселини, минерални соли, аминокиселини и витамини за подкрепа на здравето.','75.58 лв.','64.24 лв.','52.91 лв.','1026.html','https://iglika.me/products_img/Product_details_JPG/1026b.jpg','https://thealoeveraco.shop/gYkB46tG');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (26,'Добавки',1114,'207-FOREVER-BEE-HONEY','Forever Bee Honey','Пчелен мед','Вкусна съкровищница от ценни природни вещества.','38.36 лв.','32.61 лв.','26.85 лв.','1114.html','https://iglika.me/products_img/Product_details_JPG/1114b.jpg','https://thealoeveraco.shop/PjdMnmnA');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (27,'Добавки',1019,'206-FOREVER-CALCIUM','Forever Calcium','Форевър Калций','Създаден за да достави калций, витамин D и да помогне за поддържането на правилното здраве на костите.','54.94 лв.','46.70 лв.','38.46 лв.','1019.html','https://iglika.me/products_img/Product_details_JPG/1019b.jpg','https://thealoeveraco.shop/EXaSQPQi');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (28,'Добавки',1020,'065-GARLIC---TYME','Forever Garlic-Thyme','Чесън и мащерка','Съчетава всички ползи от чесъна и мащерката в едно.','41.79 лв.','35.52 лв.','29.25 лв.','1020.html','https://iglika.me/products_img/Product_details_JPG/1020b.jpg','https://thealoeveraco.shop/knIGG0bV');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (29,'Добавки',1021,'355-FOREVER-IMMUBLEND','Forever Immublend','Форевър имубленд','Всестранна хранителна добавка за подкрепа на имунитета с фруктоолигозахариди, лактоферин, гъби маитаке и шийтаке, витамини D, C и цинк.','61.25 лв.','52.06 лв.','42.88 лв.','1021.html','https://iglika.me/products_img/Product_details_JPG/1021b.jpg','https://thealoeveraco.shop/Rl4JxwNL');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (30,'Добавки',1099,'622-FOREVER-FOCUS','Forever Focus','Форевър фокус','Контролирайте сами деня си с Форевър фокус.','191.18 лв.','162.50 лв.','133.83 лв.','1099.html','https://iglika.me/products_img/Product_details_JPG/1099b.jpg','https://thealoeveraco.shop/mB7BAATW');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (31,'Добавки',1100,'551-FOREVER-MOVE','Forever Move','Форевър мув','Движете се свободно и подкрепяйте подвижността на ставите си!','143.10 лв.','121.64 лв.','100.17 лв.','1100.html','https://iglika.me/products_img/Product_details_JPG/1100b.jpg','https://thealoeveraco.shop/JkLWFa3S');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (32,'Добавки',1101,'610-FOREVER-ACTIV-PRO-B','Forever Active Pro-B','Форевър актив про-Б','Балансирана патентована комбинация от шест клинично проучени пробиотични щама.','84.12 лв.','71.50 лв.','58.88 лв.','1101.html','https://iglika.me/products_img/Product_details_JPG/1101b.jpg','https://thealoeveraco.shop/qSeDu6PY');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (33,'Добавки',1102,'354-FOREVER-KIDS','Forever Kids','Форевър кидс','Дъвчащи таблетки с витамини и минерали.','32.07 лв.','27.26 лв.','22.45 лв.','1102.html','https://iglika.me/products_img/Product_details_JPG/1102b.jpg','https://thealoeveraco.shop/K9lkL4Ym');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (34,'Добавки',1103,'439-FOREVER-DAILY','Forever Daily','Форевър дейли','Mултивитамин с възможно най-съвременната система за ефикасно усвояване на съставките.','47.53 лв.','40.40 лв.','33.27 лв.','1103.html','https://iglika.me/products_img/Product_details_JPG/1103b.jpg','https://thealoeveraco.shop/sjZIM5uZ');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (35,'Добавки',1104,'037-NATURE-MIN','Nature-Min','Нейчър-мин','Форевър нейчър-мин съдържа над 10 незаменими минерали и микроелементи, извлечени от естествена утайка от морското дъно и морски растения.','41.79 лв.','35.52 лв.','29.25 лв.','1104.html','https://iglika.me/products_img/Product_details_JPG/1104b.jpg','https://thealoeveraco.shop/oSlwE4mE');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (36,'Добавки',1105,'072-FOREVER-LYCIUM-PLUS','Forever Lycium Plus','Форевър лициум плюс','По-известен като годжи бери, лициумът е древен китайски „ин тоник“ и много силен антиоксидант.','75.58 лв.','64.24 лв.','52.91 лв.','1105.html','https://iglika.me/products_img/Product_details_JPG/1105b.jpg','https://thealoeveraco.shop/CUcSsnJG');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (37,'Добавки',1085,'676-FOREVER-TURM','Forever AloeTurm','Форевър АЛОЕТУРМ','Хидрогелни пастили със свеж вкус на мента, които бавно се разтварят в устата ви и доставят куркума, алое вера и цинк.','14.90 лв.','12.67 лв.','10.43 лв.','1085.html','https://iglika.me/products_img/Product_details_JPG/1085b.jpg','https://thealoeveraco.shop/wP6hdOv4');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (38,'Добавки',1022,'566-FOREVER-IMMUNE-GUMMY','Forever Immune Gummy','Форевър имуно гъми','Желирани бонбони с тропически вкус, които осигуряват комбинация от 10 витамина и цинк дневно.','84.69 лв.','71.99 лв.','59.28 лв.','1022.html','https://iglika.me/products_img/Product_details_JPG/1022b.jpg','https://thealoeveraco.shop/isNsyZpc');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (39,'Добавки',1023,'624-FOREVER-IVISION','Forever iVision','Форевър Айвижън','Съдържа комбинация от антиоксиданти и други хранителни вещества, които се грижат за поддържане оптималното здраве на очите.','80.12 лв.','68.10 лв.','56.08 лв.','1023.html','https://iglika.me/products_img/Product_details_JPG/1023b.jpg','https://thealoeveraco.shop/x4KSeVKp');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (40,'Добавки',1097,'312-FOREVER-CARDIOHEALTH','Forever CardioHealth','Форевър кардио здраве','Отлична хранителна добавка с коензим Q10 и специална прахообразна формула, създадена за разтваряне в гела от алое на Форевър.','68.68 лв.','58.38 лв.','48.08 лв.','1097.html','https://iglika.me/products_img/Product_details_JPG/1097b.jpg','https://thealoeveraco.shop/yZhugDoJ');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (41,'Добавки',1098,'264-FOREVER-ACTIVE-HA','Forever Active HA','Форевър активна ХК','Уникална форма на хиалуронова киселина с ниско молекулярно тегло.','69.27 лв.','58.88 лв.','48.49 лв.','1098.html','https://iglika.me/products_img/Product_details_JPG/1098b.jpg','https://thealoeveraco.shop/xmZOmmnQ');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (42,'Добавки',1024,'613-FOREVER-MARINE-COLLAGEN','Forever Marine Collagen','Форевър Морски колаген','Висококачествен морски колаген,  полезен за хидратацията на кожата, структурата и здравето и.','187.14 лв.','159.07 лв.','131.00 лв.','1024.html','https://iglika.me/products_img/Product_details_JPG/1024b.jpg','https://thealoeveraco.shop/LZsjvLkE');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (43,'Добавки',1025,'215-FOREVER-MULTI-MACA','Forever Multi-Maca','Форевър Mулти-мака','Включва внимателно подбрана смес от корени, плодове и ензими.','60.68 лв.','51.58 лв.','42.48 лв.','1025.html','https://iglika.me/products_img/Product_details_JPG/1025b.jpg','https://thealoeveraco.shop/npAImnls');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (44,'Добавки',1027,'621-SUPERGREENS','Forever Supergreens','Форевър Супергрийнс','Стимулира естествените нива на енергия и метаболизма и е богат на антиоксидантните витамини C и E.','88.12 лв.','74.90 лв.','61.68 лв.','1027.html','https://iglika.me/products_img/Product_details_JPG/1027b.jpg','https://thealoeveraco.shop/DCi4yrWn');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (45,'Добавки',1028,'374-VITOLIZE-MEN','Vitolize men','Витолайз за него','Съдържа комбинация от билки, витамини, минерали включително цинк.','68.68 лв.','58.38 лв.','48.08 лв.','1028.html','https://iglika.me/products_img/Product_details_JPG/1028b.jpg','https://thealoeveraco.shop/cloBqjlU');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (46,'Добавки',1029,'375-VITOLIZE-WOMEN','Vitolize women','Витолайз за нея','Богата на желязо, което допринася за нормалната когнитивна функция и фолиева киселина.','72.68 лв.','61.78 лв.','50.88 лв.','1029.html','https://iglika.me/products_img/Product_details_JPG/1029b.jpg','https://thealoeveraco.shop/JYmQ4bfY');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (47,'Добавки',1030,'556-INFINITE-FIRMING-COMPLEX','Infinite by Forever firming complex','Стягащ комплекс','Със съдържание на витамин C, който помага за здравословната формация на колаген в кожата, биотин за поддържане на здрава коса и кожа, и допълнителен морски колаген.','118.46 лв.','100.69 лв.','82.92 лв.','1030.html','https://iglika.me/products_img/Product_details_JPG/1030b.jpg','https://thealoeveraco.shop/OQSVJNxR');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (48,'Грижа за лицето',1031,'612-ALOE-ACTIVATOR-2018','Aloe activator','Алое активатор','Този продукт съдържа над 98% гел от алое вера, което го прави идеален за чувствителна кожа.','36.61 лв.','31.12 лв.','25.63 лв.','1031.html','https://iglika.me/products_img/Product_details_JPG/1031b.jpg','https://thealoeveraco.shop/yJ7oHqhq');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (49,'Грижа за лицето',1032,'561-AWAKENING-EYE-CREAM','Awakening eye cream','Пробуждащ околоочен крем','Предназначен да подобри и изглади чувствителната област около очите, видимо намалява появата на линии, бръчки и тъмни кръгове.','41.79 лв.','35.52 лв.','29.25 лв.','1032.html','https://iglika.me/products_img/Product_details_JPG/1032b.jpg','https://thealoeveraco.shop/aO41Tsms');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (50,'Грижа за лицето',1033,'560-BALANCING-TONER','Balancing toner','Балансиращ тоник','Помага да се балансира pH на кожата и да се премахне излишният остатък след използване на почистващи продукти.','49.78 лв.','42.31 лв.','34.85 лв.','1033.html','https://iglika.me/products_img/Product_details_JPG/1033b.jpg','https://thealoeveraco.shop/xPLE52Gf');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (51,'Грижа за лицето',1077,'664-FOREVER-BIO-CELLULOSE-MASK-X3','Aloe Bio-Cellulose Mask','Алое био-целуозна маска','Алое био-целулозната маска на Форевър осигурява интензивно и съживяващо овлажняване с напредничави технологии и натурални съставки.','72.68 лв.','61.78 лв.','50.88 лв.','1077.html','https://iglika.me/products_img/Product_details_JPG/1077b.jpg','https://thealoeveraco.shop/yhHHTSID');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (52,'Грижа за лицето',1034,'022-ALOE-LIPS-','Aloe lips','Алое липс','Най-доброто решение срещу напукани устни.','8.00 лв.','6.80 лв.','5.60 лв.','1034.html','https://iglika.me/products_img/Product_details_JPG/1034b.jpg','https://thealoeveraco.shop/n4pNKmLa');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (53,'Грижа за лицето',1035,'238-FOREVER-ALOE-SCRUB','Aloe scrub','Алое ексфолиант','Натурален ексфолиант за лице и тяло.','36.08 лв.','30.67 лв.','25.26 лв.','1035.html','https://iglika.me/products_img/Product_details_JPG/1035b.jpg','https://thealoeveraco.shop/iYlHOyTa');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (54,'Грижа за лицето',1036,'553-INFINITE-SKIN-CARE-KIT','Infinite by Forever','Инфинит от Форевър','Продуктите се грижат за това да намалят появата на фини линии и бръчки, да подобрят гладкостта на кожата и да подкрепят красотата отвътре навън.','400.64 лв.','340.54 лв.','280.45 лв.','1036.html','https://iglika.me/products_img/Product_details_JPG/1036b.jpg','https://thealoeveraco.shop/WssM5BFA');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (55,'Грижа за лицето',1037,'618-HYDRATING-SERUM','Hydrating serum','Хидратиращ серум','Продукт за грижа за кожата, предназначен да осигури максимална хидратация.','80.12 лв.','68.10 лв.','56.08 лв.','1037.html','https://iglika.me/products_img/Product_details_JPG/1037b.jpg','https://thealoeveraco.shop/EfnsGvAF');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (56,'Грижа за лицето',1038,'555-INFINITE-FIRMING-SERUM','Infinite by Forever firming serum','Инфинит стягащ серум','Допълва естествените процеси в кожата, за да увеличи здравината и да намали появата на фини линии и бръчки','119.05 лв.','101.19 лв.','83.34 лв.','1038.html','https://iglika.me/products_img/Product_details_JPG/1038b.jpg','https://thealoeveraco.shop/Ewgk3M5v');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (57,'Грижа за лицето',1039,'554-INFINITE-HYDRATING-CLEANSER','Infinite by Forever hydrating cleanser','Хидратиращ почистващ лосион','Хидратира кожата, нежно отмива мръсотията и мазнините без да изсушава.','60.11 лв.','51.09 лв.','42.08 лв.','1039.html','https://iglika.me/products_img/Product_details_JPG/1039b.jpg','https://thealoeveraco.shop/99gbQYlR');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (58,'Грижа за лицето',1040,'558-INFINITE-RESTORING-CREAM','Infinite by Forever restoring creme','Възстановяващ крем','Абсорбира се в кожата, като я оставя хидратирана и гладка.','132.77 лв.','112.85 лв.','92.94 лв.','1040.html','https://iglika.me/products_img/Product_details_JPG/1040b.jpg','https://thealoeveraco.shop/rtvqBi7o');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (59,'Грижа за лицето',1106,'653-REPLENISHING-SKIN-OIL','Replenishing Skin Oil','Възобновяващо масло за лице','Възобновяващото масло за лице е лека течност без силикони.','69.27 лв.','58.88 лв.','48.49 лв.','1106.html','https://iglika.me/products_img/Product_details_JPG/1106b.jpg','https://thealoeveraco.shop/jYzp3pc5');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (60,'Грижа за лицето',1107,'651-DEEP-MOISTURIZING-CREAM','Deep moisturizing cream','Дълбоко овлажняващ крем','Някои хидратанти са като капка вода. Този крем е като цял басейн.','76.13 лв.','64.71 лв.','53.29 лв.','1107.html','https://iglika.me/products_img/Product_details_JPG/1107b.jpg','https://thealoeveraco.shop/AIRUExZl');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (61,'Грижа за лицето',1108,'069-R3-FACTOR-SKIN-CR?ME','R3 Factor','R3 фактор','Съхранете, възстановете и обновете.','75.58 лв.','64.24 лв.','52.91 лв.','1108.html','https://iglika.me/products_img/Product_details_JPG/1108b.jpg','https://thealoeveraco.shop/LzBV8QvV');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (62,'Грижа за лицето',1109,'341-MASK-POWDER','Mask Powder','Маска за лице','Стяга и почиства порите ви в дълбочина.','43.49 лв.','36.97 лв.','30.44 лв.','1109.html','https://iglika.me/products_img/Product_details_JPG/1109b.jpg','https://thealoeveraco.shop/wjYmanXz');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (63,'Грижа за лицето',1041,'645-PROTECTING-DAY-LOTION','Protecting Day Lotion','Защитен дневен лосион','Този лосион предлага широкоспектърна SPF 20 защита и подхранва кожата.','83.57 лв.','71.03 лв.','58.50 лв.','1041.html','https://iglika.me/products_img/Product_details_JPG/1041b.jpg','https://thealoeveraco.shop/KI8xZjZk');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (64,'Грижа за лицето',1042,'559-SMOOTHING-EXFOLIATOR','Smoothing exfoliator','Изглаждащ ексфолиант','Премахва мъртвите клетки и изглажда текстурата, за по-сияеща кожа.','41.79 лв.','35.52 лв.','29.25 лв.','1042.html','https://iglika.me/products_img/Product_details_JPG/1042b.jpg','https://thealoeveraco.shop/5oHLcCUY');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (65,'Грижа за лицето',1043,'609-SONYA-DAILY-SKINCARE-KIT','Sonya daily skincare system','Ежедневна грижа за кожата "Соня"','Формулирана специално за комбинирана кожа, цялата линия осигурява най-доброто от науката и природата за всеки аспект от ежедневната ви грижа за кожата.','195.18 лв.','165.90 лв.','136.63 лв.','1043.html','https://iglika.me/products_img/Product_details_JPG/1043b.jpg','https://thealoeveraco.shop/JmeJoUgS');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (66,'Грижа за лицето',1044,'606-SONYA-ILLUMINATING-GEL','Sonya illuminating gel','Озаряващ гел','Помага за хармонизация на тена на кожата и намаляване на пигментните петна.','50.92 лв.','43.28 лв.','35.64 лв.','1044.html','https://iglika.me/products_img/Product_details_JPG/1044b.jpg','https://thealoeveraco.shop/7FQA31Yt');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (67,'Грижа за лицето',1045,'607-SONYA-REFINING-GEL-MASK','Sonya refining gel mask','Усъвършенстваща гел маска','Поддържа външния вид на кожата, контролира мазнините и озарява тена.','53.82 лв.','45.75 лв.','37.67 лв.','1045.html','https://iglika.me/products_img/Product_details_JPG/1045b.jpg','https://thealoeveraco.shop/oQqqQ6Qd');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (68,'Грижа за лицето',1046,'605-SONYA-REFRESHING-GEL-CLEANSER','Sonya refreshing gel cleanser','Освежаващ почистващ гел','Иновативен почистващ гел за лице, специално разработен за комбинирана кожа.','53.82 лв.','45.75 лв.','37.67 лв.','1046.html','https://iglika.me/products_img/Product_details_JPG/1046b.jpg','https://thealoeveraco.shop/yuqyGUvl');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (69,'Грижа за лицето',1047,'608-SONYA-SOOTHING-GEL-MOISTURIZER','Sonya soothing gel moisturizer','Успокояващ овлажняващ гел','Осигурява мощно успокояващо и овлажняващо действие за комбинирана кожа.','58.96 лв.','50.12 лв.','41.27 лв.','1047.html','https://iglika.me/products_img/Product_details_JPG/1047b.jpg','https://thealoeveraco.shop/EUmgbaA3');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (70,'Грижа за тялото',1048,'647-ALOE-BODY-LOTION','Aloe Body Lotion','Алое лосион за тяло','Ежедневен овлажняващ продукт, който омекотява кожата и я оставя хидратирана и здрава.','52.04 лв.','44.23 лв.','36.43 лв.','1048.html','https://iglika.me/products_img/Product_details_JPG/1048b.jpg','https://thealoeveraco.shop/ZtGsCQE7');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (71,'Грижа за тялото',1049,'564-ALOE-COOLING-LOTION','Aloe Cooling lotion','Aлое oхлаждащ лосион','Предоставя охлаждащо усещане с освежаващ ментов аромат.','34.34 лв.','29.19 лв.','24.04 лв.','1049.html','https://iglika.me/products_img/Product_details_JPG/1049b.jpg','https://thealoeveraco.shop/gjtFnOdL');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (72,'Грижа за тялото',1050,'040-ALOE-FIRST-SPRAY','Aloe First','Алое Фърст','Успокояващ продукт за грижа за кожата, съдържащ гел от алое вера, пчелен прополис и единадесет полезни билкови екстракта.','45.24 лв.','38.45 лв.','31.67 лв.','1050.html','https://iglika.me/products_img/Product_details_JPG/1050b.jpg','https://thealoeveraco.shop/3PFVOgov');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (73,'Грижа за тялото',1051,'205-ALOE-MSM-GEL','Aloe MSM Gel','Алое МСМ гел','Предназначен за облекчаване на ставни и мускулни болки.','52.68 лв.','44.78 лв.','36.88 лв.','1051.html','https://iglika.me/products_img/Product_details_JPG/1051b.jpg','https://thealoeveraco.shop/XZsXABV6');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (74,'Грижа за тялото',1052,'051-ALOE-PROPOLIS-CREME','Aloe Propolis Creme','Алое Прополис крем','Витамините A, E и C работят за подхранване и овлажняване на кожата, докато прополисът помага за подмладяване на кожата.','45.24 лв.','38.45 лв.','31.67 лв.','1052.html','https://iglika.me/products_img/Product_details_JPG/1052b.jpg','https://thealoeveraco.shop/ECbIhri2');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (75,'Грижа за тялото',1110,'063-ALOE-MOISTURIZING-LOTION','Aloe Moisturizing Lotion','Овлажняващ алое лосион','Съдържа 100% стабилизиран гел от алое вера, алантоин, масло от кайсиеви ядки, масло от жожоба.','34.34 лв.','29.19 лв.','24.04 лв.','1110.html','https://iglika.me/products_img/Product_details_JPG/1110b.jpg','https://thealoeveraco.shop/fyrdPQ48');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (76,'Грижа за тялото',1053,'617-SUNSCREEN-LOTION-MIT-FREE','Aloe sunscreen','Алое Сънскрийн','Този слънцезащитен продукт предлага водоустойчива SPF 30 защита от UVA и UVB лъчи, плюс успокояващата сила на алое.','47.53 лв.','40.40 лв.','33.27 лв.','1053.html','https://iglika.me/products_img/Product_details_JPG/1053b.jpg','https://thealoeveraco.shop/1OSy2WWE');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (77,'Грижа за тялото',1054,'061-ALOE-VERA-GELLY','Aloe Vera Gelly','Алое Вера гел Джели','Почти идентичен с вътрешността на листата на алое вера, овлажнява, подхранва и успокоява кожата','34.34 лв.','29.19 лв.','24.04 лв.','1054.html','https://iglika.me/products_img/Product_details_JPG/1054b.jpg','https://thealoeveraco.shop/roNsrpy8');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (78,'Лична хигиена',1055,'284-AVOCADO-SOAP','Aloe Avocado Face & Body Soap','Алое и авокадо сапун за лице и тяло','Достатъчно нежен за цялото ви тяло и лице с аромат на свежо набрани цитрусови плодове.','13.76 лв.','11.70 лв.','9.63 лв.','1055.html','https://iglika.me/products_img/Product_details_JPG/1055b.jpg','https://thealoeveraco.shop/s8ZWEVvg');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (79,'Лична хигиена',1079,'644-MALOSI-MENS-COLOGNE','Forever Malosi Fine Frangrance for Him','Парфюм "Малоси" за него','Обгърнете сетивата си със силата на любовта на островите Самоа с помощта на този изключителен фин парфюм, който отдава почит към основателя на Форевър Рекс Моън и неговата дълбока връзка с народа на Самоа.','76.69 лв.','65.19 лв.','53.68 лв.','1079.html','https://iglika.me/products_img/Product_details_JPG/1079b.jpg','https://thealoeveraco.shop/jVJsgCSY');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (80,'Лична хигиена',1080,'643-ALOFA-WOMENS-PERFUME','Forever Alofa Fine Frangrance for Her','Парфюм "Алофа" за нея','Обгърнете сетивата си със силата на любовта на островите Самоа с помощта на този изключителен фин парфюм, който отдава почит към основателя на Форевър Рекс Моън и неговата дълбока връзка с народа на Самоа.','76.69 лв.','65.19 лв.','53.68 лв.','1080.html','https://iglika.me/products_img/Product_details_JPG/1080b.jpg','https://thealoeveraco.shop/9CRF6XuI');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (81,'Лична хигиена',1081,'642-NOURISHING-HAIR-OIL','Nourishing Hair Oil','Подхранващо масло за коса','Шест растителни масла без силикони предлагат хидратация и подхранване.','63.52 лв.','53.99 лв.','44.46 лв.','1081.html','https://iglika.me/products_img/Product_details_JPG/1081b.jpg','https://thealoeveraco.shop/fjnCN4Nl');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (82,'Лична хигиена',1115,'067-ALOE-EVER-SHIELD-DEODORANT','Aloe Ever-Shield Deodorant Stick','Сух алое дезодорант','Нежната формула със стабилизиран гел от алое вера не съдържа вредни алуминиеви соли.','16.60 лв.','14.11 лв.','11.62 лв.','1115.html','https://iglika.me/products_img/Product_details_JPG/1115b.jpg',NULL);
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (83,'Лична хигиена',1056,'646-ALOE-BODY-WASH','Aloe Body Wash','Алое Душ-гел','Формула без сулфати предлага мощно, но нежно почистване със съставки които подхранват кожата, отмиват мръсотията и я оставят мека и освежена.','51.49 лв.','43.77 лв.','36.04 лв.','1056.html','https://iglika.me/products_img/Product_details_JPG/1056b.jpg','https://thealoeveraco.shop/InT3CF0j');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (84,'Лична хигиена',1057,'633-ALOE-LIQUID-SOAP-','Aloe Liquid Soap','Алое течен сапун','Овлажнява и почиства, оставяйки кожата ви по-мека, по-гладка и по-сияйна.','42.92 лв.','36.48 лв.','30.04 лв.','1057.html','https://iglika.me/products_img/Product_details_JPG/1057b.jpg','https://thealoeveraco.shop/8igYrjiD');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (85,'Лична хигиена',1058,'640-ALOE-JOJOBA-SHAMPOO','Aloe-Jojoba Shampoo','Алое-жожоба шампоан','Направен с чист алое вера гел и укрепващо жожоба масло, този шампоан е перфектен за ежедневна употреба,','49.78 лв.','42.31 лв.','34.85 лв.','1058.html','https://iglika.me/products_img/Product_details_JPG/1058b.jpg','https://thealoeveraco.shop/6agzL7H2');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (86,'Лична хигиена',1059,'641-ALOE-JOJOBA-CONDITIONER','Aloe-Jojoba Conditioner','Алое-жожоба балсам','Подхранва и хидратира в дълбочина, като омекотява, изглажда и прави косата по-лесна за разресване.','53.25 лв.','45.26 лв.','37.28 лв.','1059.html','https://iglika.me/products_img/Product_details_JPG/1059b.jpg','https://thealoeveraco.shop/9h5lWUXz');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (87,'Лична хигиена',1060,'028-FOREVER-BRIGHT-TOOTH-GEL','Forever Bright Toothgel','Гел за зъби Форевър брайт','Формулата без флуорид оставя след себе си усещане за свежест и чистота.','17.74 лв.','15.08 лв.','12.42 лв.','1060.html','https://iglika.me/products_img/Product_details_JPG/1060b.jpg','https://thealoeveraco.shop/uLEp2bNe');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (88,'Лична хигиена',1061,'070-GENTLEMANS-PRIDE-AFTERSHAVE','Gentleman’s Pride After Shave Balm','Балсам за след бръснене','Предлага ексклузивна комбинация от съставки, които осигуряват охлаждащо усещане и прекрасен аромат.','34.34 лв.','29.19 лв.','24.04 лв.','1061.html','https://iglika.me/products_img/Product_details_JPG/1061b.jpg','https://thealoeveraco.shop/jEqNntlS');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (89,'Пакети',1063,'001-A-TOUCH-OF-FOREVER','Touch of Forever','Докосване до Форевър','Троен пакет Гел от Алое Вера!','1 116.34 лв.','948.89 лв.','781.44 лв.','1063.html','https://iglika.me/products_img/Product_details_JPG/1063b.jpg','https://thealoeveraco.shop/voZ2evix');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (90,'Пакети',1065,NULL,'Start Your Journey Pack','Пакет „Стартирай пътешествието си“',NULL,'823.36 лв.','699.86 лв.','823.36 лв.','1065.html','https://iglika.me/products_img/Product_details_JPG/1065b.jpg','https://thealoeveraco.shop/hIVFXEwG');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (91,'Пакети',1064,'71633-ARGI-AND-ALOE-MINI-TRIPACK','ARGI+ & Aloe Mini TriPak','ТриПак АРГИ+ и Алое мини','Троен пакет Алое Праскова!','75.19 лв.','63.91 лв.','52.63 лв.','1064.html','https://iglika.me/products_img/Product_details_JPG/1064b.jpg','https://thealoeveraco.shop/Q1izQaIu');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (92,'Пакети',1083,'456-VITAL-5','Vital5/Aloe Vera Gel','Витал 5/Алое Вера гел','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','555.54 лв.','472.21 лв.','388.88 лв.','1083.html','https://iglika.me/products_img/Product_details_JPG/1083b.jpg','https://thealoeveraco.shop/KfnkAqqk');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (93,'Пакети',1096,'457-VITAL-5-BERRY','Vital5/Aloe Berry Nectar','Витал 5/Алое Бери нектар','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','555.54 лв.','472.21 лв.','388.88 лв.','1096.html','https://iglika.me/products_img/Product_details_JPG/1096b.jpg','https://thealoeveraco.shop/pSUSDRu6');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (94,'Пакети',1074,'529-F15-BEGINNER-12-CHOCOLATE','F15 Beginner/Chocolate','Ф15 Начинаещи/Шоколад','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','337.32 лв.','286.72 лв.','236.12 лв.','1074.html','https://iglika.me/products_img/Product_details_JPG/1074b.jpg','https://thealoeveraco.shop/iUAcpdl3');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (95,'Пакети',1086,'528-F15-BEGINNER-12-VANILLA','F15 Beginner/Vanilla','Ф15 Начинаещи/Ванилия','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','337.32 лв.','286.72 лв.','236.12 лв.','1086.html','https://iglika.me/products_img/Product_details_JPG/1086b.jpg','https://thealoeveraco.shop/85Mxzokm');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (96,'Пакети',1087,'533-F15-INTEBEGINNER-12-CHOCOLATE','F15 Intermediate/Chocolate','Ф15 Средно напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1087.html','https://iglika.me/products_img/Product_details_JPG/1074b.jpg','https://thealoeveraco.shop/uJ2W3qgd');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (97,'Пакети',1088,'532-F15-INTERMEDIATE-12-VANILLA','F15 Intermediate/Vanilla','Ф15 Средно напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1088.html','https://iglika.me/products_img/Product_details_JPG/1086b.jpg','https://thealoeveraco.shop/8n6lRvsU');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (98,'Пакети',1089,'537-F15-ADVANCED-12-CHOCOLATE','F15 Advanced/Chocolate','Ф15 Напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1089.html','https://iglika.me/products_img/Product_details_JPG/1074b.jpg','https://thealoeveraco.shop/UMWgAiQK');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (99,'Пакети',1090,'536-F15-ADVANCED-12-VANILLA','F15 Advanced/Vanilla','Ф15 Напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1090.html','https://iglika.me/products_img/Product_details_JPG/1086b.jpg','https://thealoeveraco.shop/2nUDNCS1');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (100,'Пакети',1073,'475-C9-GEL-VANILLA','Clean-9/Gel-Vanilla','Клийн-9/Алое Вера гел-Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','270.32 лв.','229.77 лв.','189.22 лв.','1073.html','https://iglika.me/products_img/Product_details_JPG/1073b.jpg','https://thealoeveraco.shop/BzXELmWS');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (101,'Пакети',1091,'476-C9-GEL-CHOCOLATE','Clean-9/Gel-Chocolate','Клийн-9/Алое Вера гел-Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','270.32 лв.','229.77 лв.','189.22 лв.','1091.html','https://iglika.me/products_img/Product_details_JPG/1091b.jpg','https://thealoeveraco.shop/Ii4Jppg7');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (102,'Пакети',1092,'625-C9-BERRY-VANILLA','Clean-9/Berry-Vanilla','Клийн-9/Алое Бери нектар-Ванилия','Пакет от популярни продукти от Forever Living Products, предназначени да ви запознаят с предложенията на марката.','270.32 лв.','229.77 лв.','189.22 лв.','1092.html','https://iglika.me/products_img/Product_details_JPG/1092b.jpg','https://thealoeveraco.shop/LKZEM9bu');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (103,'Пакети',1093,'626-C9-BERRY-CHOCOLATE','Clean-9/Berry-Chocolate','Клийн-9/Алое Бери нектар-Шоколад','Ако търсите начин да започнете собствен Форевър бизнес или да пазарувате продуктите на Форевър Ливинг с 30% отстъпка, този пакет може да ви заинтригува.','270.32 лв.','229.77 лв.','189.22 лв.','1093.html','https://iglika.me/products_img/Product_details_JPG/1093b.jpg','https://thealoeveraco.shop/jV6PoGDS');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (104,'Пакети',1094,'629-C9-PEACH-VANILLA','Clean-9/Peach-Vanilla','Клийн-9/Алое Праскова-Ванилия','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен ванилов вкус.','270.32 лв.','229.77 лв.','189.22 лв.','1094.html','https://iglika.me/products_img/Product_details_JPG/1094b.jpg','https://thealoeveraco.shop/N000Bh2N');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (105,'Пакети',1095,'630-C9-PEACH-CHOCOLATE','Clean-9/Peach-Chocolate','Клийн-9/Алое Праскова-Шоколад','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен шоколадов вкус.','270.32 лв.','229.77 лв.','189.22 лв.','1095.html','https://iglika.me/products_img/Product_details_JPG/1095b.jpg','https://thealoeveraco.shop/C637wOsi');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (106,'Пакети',1072,'659-DX-4','DX4 Body Balancing System','DX4 Балансираща програма','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','320.50 лв.','272.43 лв.','224.35 лв.','1072.html','https://iglika.me/products_img/Product_details_JPG/1072b.jpg','https://thealoeveraco.shop/wcHFYOEU');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (107,'Контрол на теглото',1066,'471-FOREVER-LITE-ULTRA-CHOCOLAT-15','Forever Lite Ultra with Aminotein chocolate','Форевър лайт ултра с аминотеин шоколад','В пакета получавате ГЕЛА ОТ АЛОЕ ВЕРА заедно с АЛОЕ И ПРАСКОВИ и АЛОЕ БЕРИ НЕКТАР с неговия свеж и богат на антиоксиданти вкус, подкрепящ нормалното храносмилане.','57.23 лв.','48.65 лв.','40.06 лв.','1066.html','https://iglika.me/products_img/Product_details_JPG/1066b.jpg','https://thealoeveraco.shop/uZynN4p7');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (108,'Контрол на теглото',1067,'470-FOREVER-LITE-ULTRA-VANILLA-15','Forever Lite Ultra with Aminotein vanilla','Форевър лайт ултра с аминотеин ванилия','В пакета ще откриете три мини опаковки гел от алое вера по 330 мл и три пакетчета Арги+.','57.23 лв.','48.65 лв.','40.06 лв.','1067.html','https://iglika.me/products_img/Product_details_JPG/1067b.jpg','https://thealoeveraco.shop/jOSgdtZX');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (109,'Контрол на теглото',1068,'656-FOREVER-PLANT-PROTEIN-POUCH','Forever Plant Protein','Форевър Растителен протеин','Четиридневна програма, която помага за рестартиране на вашето физическо, ментално и духовно здраве чрез седем хранителни продукта, практики за установяване на мисленето и ръководство за приемане на храната.','127.62 лв.','108.48 лв.','89.33 лв.','1068.html','https://iglika.me/products_img/Product_details_JPG/1068b.jpg','https://thealoeveraco.shop/6BAPwHSh');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (110,'Контрол на теглото',1069,'665-FOREVER-SENSATIABLE','Forever Sensatiable','Форевър Сенсейшабъл','Програма Vital5 е нашето решение за пълноценно хранене в един удобен пакет.','60.11 лв.','51.09 лв.','42.08 лв.','1069.html','https://iglika.me/products_img/Product_details_JPG/1069b.jpg','https://thealoeveraco.shop/O6YypbKS');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (111,'Контрол на теглото',1070,'289-FOREVER-LEAN','Forever Lean','Форевър Лийн','Програма Vital5 е нашето решение за пълноценно хранене в един удобен пакет.','86.44 лв.','73.47 лв.','60.51 лв.','1070.html','https://iglika.me/products_img/Product_details_JPG/1070b.jpg','https://thealoeveraco.shop/ChtZcctu');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (112,'Контрол на теглото',1071,'520-FAST-BREAK-BARS','Forever FastBreak','Форевър Фаст Брейк','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','10.31 лв.','8.76 лв.','7.22 лв.','1071.html','https://iglika.me/products_img/Product_details_JPG/1071b.jpg','https://thealoeveraco.shop/fHDy4fww');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (113,'Контрол на теглото',1111,'463-FOREVER-THERM','Forever Therm','Форевър терм','Зелен чай, гуарана и натурален кофеин ви зареждат с енергия и стимулират метаболизма ви.','79.54 лв.','67.61 лв.','55.68 лв.','1111.html','https://iglika.me/products_img/Product_details_JPG/1111b.jpg','https://thealoeveraco.shop/yo7w1dl1');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (114,'Контрол на теглото',1112,'071-GARCINIA-PLUS','Forever Garcinia Plus','Форевър гарциния плюс','Възпрепятства преобразуването на въглехидратите в мастни тъкани.','75.58 лв.','64.24 лв.','52.91 лв.','1112.html','https://iglika.me/products_img/Product_details_JPG/1112b.jpg','https://thealoeveraco.shop/0pVzCab2');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (115,'Контрол на теглото',1113,'464-FOREVER-FIBER-30','Forever Fiber','Форевър фибри','Лесно добавяйте фибри към всекидневния си режим с нашите удобни пакетчета.','51.51 лв.','43.78 лв.','36.06 лв.','1113.html','https://iglika.me/products_img/Product_details_JPG/1113b.jpg','https://thealoeveraco.shop/MBS0gCQ2');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (116,'Контрол на теглото',1074,'529-F15-BEGINNER-12-CHOCOLATE','F15 Beginner/Chocolate','Ф15 Начинаещи/Шоколад','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','337.32 лв.','286.72 лв.','236.12 лв.','1074.html','https://iglika.me/products_img/Product_details_JPG/1074b.jpg','https://thealoeveraco.shop/iUAcpdl3');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (117,'Контрол на теглото',1086,'528-F15-BEGINNER-12-VANILLA','F15 Beginner/Vanilla','Ф15 Начинаещи/Ванилия','15-дневна програма за напреднали в областта на храненето и фитнеса, която може да ви помогне да промените своята рутина за фитнес и хранене.','337.32 лв.','286.72 лв.','236.12 лв.','1086.html','https://iglika.me/products_img/Product_details_JPG/1086b.jpg','https://thealoeveraco.shop/85Mxzokm');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (118,'Контрол на теглото',1087,'533-F15-INTEBEGINNER-12-CHOCOLATE','F15 Intermediate/Chocolate','Ф15 Средно напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1087.html','https://iglika.me/products_img/Product_details_JPG/1074b.jpg','https://thealoeveraco.shop/uJ2W3qgd');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (119,'Контрол на теглото',1088,'532-F15-INTERMEDIATE-12-VANILLA','F15 Intermediate/Vanilla','Ф15 Средно напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1088.html','https://iglika.me/products_img/Product_details_JPG/1086b.jpg','https://thealoeveraco.shop/8n6lRvsU');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (120,'Контрол на теглото',1089,'537-F15-ADVANCED-12-CHOCOLATE','F15 Advanced/Chocolate','Ф15 Напреднали/Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1089.html','https://iglika.me/products_img/Product_details_JPG/1074b.jpg','https://thealoeveraco.shop/UMWgAiQK');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (121,'Контрол на теглото',1090,'536-F15-ADVANCED-12-VANILLA','F15 Advanced/Vanilla','Ф15 Напреднали/Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','337.32 лв.','286.72 лв.','236.12 лв.','1090.html','https://iglika.me/products_img/Product_details_JPG/1086b.jpg','https://thealoeveraco.shop/2nUDNCS1');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (122,'Контрол на теглото',1073,'475-C9-GEL-VANILLA','Clean-9/Gel-Vanilla','Клийн-9/Алое Вера гел-Ванилия','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','270.32 лв.','229.77 лв.','189.22 лв.','1073.html','https://iglika.me/products_img/Product_details_JPG/1073b.jpg','https://thealoeveraco.shop/BzXELmWS');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (123,'Контрол на теглото',1091,'476-C9-GEL-CHOCOLATE','Clean-9/Gel-Chocolate','Клийн-9/Алое Вера гел-Шоколад','Програмата включва различни продукти, които ще ви помогнат да постигнете вашите цели за отслабване, както и физически упражнения.','270.32 лв.','229.77 лв.','189.22 лв.','1091.html','https://iglika.me/products_img/Product_details_JPG/1091b.jpg','https://thealoeveraco.shop/Ii4Jppg7');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (124,'Контрол на теглото',1092,'625-C9-BERRY-VANILLA','Clean-9/Berry-Vanilla','Клийн-9/Алое Бери нектар-Ванилия','Пакет от популярни продукти от Forever Living Products, предназначени да ви запознаят с предложенията на марката.','270.32 лв.','229.77 лв.','189.22 лв.','1092.html','https://iglika.me/products_img/Product_details_JPG/1092b.jpg','https://thealoeveraco.shop/LKZEM9bu');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (125,'Контрол на теглото',1093,'626-C9-BERRY-CHOCOLATE','Clean-9/Berry-Chocolate','Клийн-9/Алое Бери нектар-Шоколад','Ако търсите начин да започнете собствен Форевър бизнес или да пазарувате продуктите на Форевър Ливинг с 30% отстъпка, този пакет може да ви заинтригува.','270.32 лв.','229.77 лв.','189.22 лв.','1093.html','https://iglika.me/products_img/Product_details_JPG/1093b.jpg','https://thealoeveraco.shop/jV6PoGDS');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (126,'Контрол на теглото',1094,'629-C9-PEACH-VANILLA','Clean-9/Peach-Vanilla','Клийн-9/Алое Праскова-Ванилия','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен ванилов вкус.','270.32 лв.','229.77 лв.','189.22 лв.','1094.html','https://iglika.me/products_img/Product_details_JPG/1094b.jpg','https://thealoeveraco.shop/N000Bh2N');
INSERT INTO forever_table(amount_p,category,id,forever_name,h1,h2,description,price,discount15,discount30,url,image3,forever_url_Rumen) VALUES (127,'Контрол на теглото',1095,'630-C9-PEACH-CHOCOLATE','Clean-9/Peach-Chocolate','Клийн-9/Алое Праскова-Шоколад','Протеинова добавка, която предоставя 17 грама протеин от растителен източник на порция със страхотен шоколадов вкус.','270.32 лв.','229.77 лв.','189.22 лв.','1095.html','https://iglika.me/products_img/Product_details_JPG/1095b.jpg','https://thealoeveraco.shop/C637wOsi');
